# site name
siteName: Su's blog
shortName:  小苏


# full https model which means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
fullHttps: true

# favicon
favicon: /images/favicon.ico
# unique avatar
avatarShow: true
avatarImage: /images/favicon.png

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number
homeArticleShown: 10


# your site build time or domain buy time
siteBuildingTime: 01/20/2018


# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
   前端: front-end
   后台: back-end
   设计: product-design
   其他: others

# Left menu of single pages settings
## Notice: faName is FontAwesome style name
leftPagesMenu:
- uri: help
  title: 帮助
  faName: fa-question-circle


# cover info config
coverTitle: 好久不见
coverDescription: 来自一个极懒的前端程序员的、 bug＆踩坑血泪史。

# SNS Share Switch
# sns_share:  #用于定义分享菜单中的项目， false 的项将不会显示在分享菜单中。
#     twitter: true
#     facebook: true
#     googleplus: true
#     weibo: true
#     linkedin: true
#     qq: true
#     telegram: true
#     jianshu: true

# sns url
sns:
  # telegram: ???
  # instagram: ???
  # twitter: ???
  # jianshu: ???
  github: https://github.com/syc-xiaosu03
  weibo: http://t.me/kunyintang


# your article copyright or content declare
postDeclare: 本文代表个人观点，内容仅供参考。若有不恰当之处，望不吝赐教！

# Git-pages server info
pageServerName: Coding
pageServerUrl: https://coding.net/register?key=bcace447-fa41-4579-9783-86fdf0f723e2


# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
gitment:
  enable: false
  githubID:
  repo:
  ClientID:
  ClientSecret:
  lazy: true

## Comments settings.You can choose only ONE to display.
# disqus shortName,
disqus_shortname: shuoit 

# Analytics
tentcentAnalyticsId: 65036274
